---
- name: Install ubuntu packages
  apt:
      name: [ubuntu-restricted-extras, imagemagick, curl, git, sshfs, vim, zenity, mpv, syncthing, syncthing-gtk, chrome-gnome-shell, keepassxc, vim-gtk3, fzf, universal-ctags, mlocate, filezilla]
  become: True
  become_user: root

- name: Create screenshot directories
  file:
      path: "{{ item }}"
      state: directory
      mode: 0755
  loop:
    - $HOME/Pictures/screenshots

- name: Open pgp files with seahorse
  command: xdg-mime default org.gnome.seahorse.Application.desktop application/pgp-keys
