---
- name: Install ubuntu packages
  apt:
      name: [ubuntu-restricted-extras, imagemagick, curl, git, sshfs, vim, zenity, mpv, syncthing, syncthing-gtk, chrome-gnome-shell, keepassxc, vim-gtk3, fzf, universal-ctags, mlocate, filezilla, bsdutils, python3-pip, asciinema]
  become: True
  become_user: root
  tags: packages

- name: Create custom directories
  file:
      path: "{{ item }}"
      state: directory
      mode: 0755
  loop:
    - $HOME/Pictures/screenshots
    - $HOME/Documents/terminal_logs

- name: Copy bashrc
  template:
      src: bashrc.j2
      dest: $HOME/.bashrc

- name: Copy asciinema config file
  copy:
      src:  "asciinema_config"
      dest: "$HOME/.config/asciinema/config" 

- name: Copy asciinema player config files
  copy:
      src:  "{{ item }}"
      dest: "$HOME/Documents/terminal_logs"
  loop:
      - "asciinema-player.css"
      - "asciinema-player.min.js"
      - "asciinema_player.html"

- name: Open pgp files with seahorse
  command: xdg-mime default org.gnome.seahorse.Application.desktop application/pgp-keys

- name: Create cronjob to zip up logs from terminal recording program
  cron:
      name: "zip terminal logs"
      job: "find $HOME/Documents/terminal_logs -mtime +7 ! -name 'asciinema*' -exec bzip2 {} \\;"
      hour: "13"
      minute: "0"
