---
- name: Add skype apt key
  apt_key:
      url: https://repo.skype.com/data/SKYPE-GPG-KEY
      state: present
  become: True
  become_user: root

- name: Install skype repo
  apt_repository:
      repo: deb [arch=amd64] https://repo.skype.com/deb stable main
      state: present
  become: True
  become_user: root

- name: Add slack apt key
  apt_key:
      url: https://packagecloud.io/slacktechnologies/slack/gpgkey
      state: present
  become: True
  become_user: root

- name: Install slack repo
  apt_repository:
      repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
      state: present
  become: True
  become_user: root

# https://protonvpn.com/support/linux-ubuntu-vpn-setup/
- name: Install protonvpn repo
  apt:
      deb: https://protonvpn.com/download/protonvpn-stable-release_1.0.1-1_all.deb
  tags: packages
  become: True
  become_user: root

- name: Install ubuntu packages
  apt:
      name: "{{ item }}"
      update_cache: yes
  become: True
  become_user: root
  tags: packages
  loop: 
    - ubuntu-restricted-extras
    - imagemagick
    - curl
    - git
    - sshfs
    - vim
    - zenity
    - mpv
    - syncthing
    - syncthing-gtk
    - chrome-gnome-shell
    - keepassxc
    - vim-gtk3
    - fzf
    - universal-ctags
    - mlocate
    - filezilla
    - bsdutils
    - python3-pip
    - asciinema
    - slack-desktop
    - skypeforlinux
    - xclip
    - protonvpn

- name: Install desktop specific ubuntu packages 
  apt:
      name:
        - steam-devices
        - steam-installer
      update_cache: yes
  become: True
  become_user: root
  tags: packages
  when: '"XPS" not in ansible_hostname'

- name: Install laptop specific ubuntu packages 
  apt:
      name:
          - powertop
      update_cache: yes
  become: True
  become_user: root
  tags: packages
  when: '"XPS" in ansible_hostname'

- name: Update snap packager
  command: snap refresh
  become: True
  become_user: root

# need to install snaps one by one because of this bug
# https://forum.snapcraft.io/t/trying-to-re-install-multiple-packages-with-snap-install-fails-with-install-refresh-information-results-from-the-store/24859
- name: Install ubuntu snap packages - zoom
  command: snap install zoom-client
  become: True
  become_user: root

- name: Install ubuntu snap packages - acestreamplayer
  command: snap install acestreamplayer
  become: True
  become_user: root


- name: Create custom directories
  file:
      path: "{{ item }}"
      state: directory
      mode: 0755
  loop:
    - $HOME/Pictures/screenshots
    - $HOME/Documents/terminal_logs
    - $HOME/.config/mpv
    - $HOME/.config/asciinema
    - $HOME/.local/share/nautilus/scripts

- name: Copy bashrc
  template:
      src: bashrc.j2
      dest: $HOME/.bashrc
  tags: config

- name: Copy HOME .config files
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
  loop:
      - { src: "asciinema_config", dest: "$HOME/.config/asciinema/config" }
      - { src: "vimrc", dest: "$HOME/.vimrc" }
      - { src: "mpv.conf", dest: "$HOME/.config/mpv" }
  tags: config

- name: Copy asciinema player config files
  copy:
      src:  "{{ item }}"
      dest: "$HOME/Documents/terminal_logs"
  loop:
      - "asciinema-player.css"
      - "asciinema-player.min.js"
      - "asciinema_player.html"
  tags: config

- name: Open pgp files with seahorse
  command: xdg-mime default org.gnome.seahorse.Application.desktop application/pgp-keys

- name: Create cronjob to zip up logs from terminal recording program
  cron:
      name: "zip terminal logs"
      job: "find $HOME/Documents/terminal_logs -mtime +7 ! -name 'asciinema*' -exec bzip2 {} \\;"
      hour: "13"
      minute: "0"
  tags: cron

- name: Create cronjob to download wiki from my site
  cron:
      name: "download wiki from my site"
      job: "wget --header='X-DW-Token: {{ vault_dw_token }}' https://dw.exitstatus0.com/backup/dokuwiki.tar.bz2 --output-document=/home/antisa/dokuwiki.tar.bz2"
      hour: "19"
      minute: "0"
  tags: cron

- name: Copy opensubtitlesdownload script
  template:
      src: opensubtitles.j2
      dest: $HOME/.local/share/nautilus/scripts/opensubtitles.py
  tags: scripts

- name: Copy other useful nautilus scripts
  copy:
      src:  "{{ item }}"
      dest: "$HOME/.local/share/nautilus/scripts"
      mode: 0755
  loop:
      - "nautilus-renamer.py"
      - "nautilus-resize-image"
      - "asciivideo.sh"
  tags: scripts

- name: Mount backup disk at startup
  mount:
      path: /mnt/backup
      state: present
      src: UUID=f1a236ec-0809-4c61-b9c4-bee4427e728f
      fstype: ext4
      opts: defaults,noatime
  become: True
  become_user: root

- name: Mount touro disk at startup
  mount:
      path: /mnt/touro
      state: present
      src: root@192.168.99.143:/media/touro
      fstype: fuse.sshfs
      opts: noauto,user,x-systemd.automount,defaults,_netdev,allow_other,identityfile=/root/.ssh/id_ed25519
  become: True
  become_user: root

- name: Add raspberrypis host key to the root user
  known_hosts:
      path: /root/.ssh/known_hosts
      name: raspberrypi_3b+
      key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJH7iLv2mwvJ7ERSnrjdADbBzLF2Xo9dxANk9Vt+nY5bNTjrXNsm96Dc9U8g087TSkfYv8sLBQ9p7XKJieA0foo=
      state: present
  become: True
  become_user: root

- name: Generate ssh key for root user
  command: 
    cmd: ssh-keygen -t ed25519  -q -f "/root/.ssh/id_ed25519" -N ""
    creates: "/root/.ssh/id_ed25519"
  become: True
  become_user: root

- name: Copy root user ssh keys to rpi
  copy:
      src: "{{ lookup('file', '/root/.ssh/id_ed25519.pub') }}" 
      dest: /root/.ssh/authorized_keys
  delegate_to: 192.168.99.143

- name: Copy custom Gnome keyboard shortcuts file
  copy: 
    src: custom-shortcuts.conf
    dest: /tmp/
  tags: config

- name: Import custom Gnome keyboard shortcuts
  shell: dconf load / < /tmp/custom-shortcuts.conf
  tags: config

- name: Set other Gnome keyboard shortcuts
  shell: dconf write /org/gnome/terminal/legacy/keybindings/prev-tab "'<Alt>Left'" && \
         dconf write /org/gnome/terminal/legacy/keybindings/next-tab "'<Alt>Right'" && \
         dconf write /org/gnome/terminal/legacy/keybindings/move-tab-left "'<Shift><Alt>Left'" && \
         dconf write /org/gnome/terminal/legacy/keybindings/move-tab-right "'<Shift><Alt>Right'"
  tags: config

