---
- name: Add skype apt key
  apt_key:
      url: https://repo.skype.com/data/SKYPE-GPG-KEY
      state: present
  become: True
  become_user: root

- name: Install skype repo
  apt_repository:
      repo: deb [arch=amd64] https://repo.skype.com/deb stable main
      state: present
  become: True
  become_user: root

- name: Add slack apt key
  apt_key:
      url: https://packagecloud.io/slacktechnologies/slack/gpgkey
      state: present
  become: True
  become_user: root

- name: Install slack repo
  apt_repository:
      repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
      state: present
  become: True
  become_user: root

- name: Install ubuntu packages
  apt:
      name: [ubuntu-restricted-extras, imagemagick, curl, git, sshfs, vim, zenity, mpv, syncthing, syncthing-gtk, chrome-gnome-shell, keepassxc, vim-gtk3, fzf, universal-ctags, mlocate, filezilla, bsdutils, python3-pip, asciinema, skypeforlinux, slack-desktop]
      update_cache: yes
  become: True
  become_user: root
  tags: packages

- name: Update snap packager
  command: snap refresh
  become: True
  become_user: root

# need to install snaps one by one because of this bug
# https://forum.snapcraft.io/t/trying-to-re-install-multiple-packages-with-snap-install-fails-with-install-refresh-information-results-from-the-store/24859
- name: Install ubuntu snap packages - zoom
  command: snap install zoom-client
  become: True
  become_user: root

- name: Install ubuntu snap packages - acestreamplayer
  command: snap install acestreamplayer
  become: True
  become_user: root


- name: Create custom directories
  file:
      path: "{{ item }}"
      state: directory
      mode: 0755
  loop:
    - $HOME/Pictures/screenshots
    - $HOME/Documents/terminal_logs
    - $HOME/.config/mpv
    - $HOME/.config/asciinema
    - $HOME/.local/share/nautilus/scripts

- name: Copy bashrc
  template:
      src: bashrc.j2
      dest: $HOME/.bashrc

- name: Copy HOME .config files
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
  loop:
      - { src: "asciinema_config", dest: "$HOME/.config/asciinema/config" }
      - { src: "vimrc", dest: "$HOME/.vimrc" }
      - { src: "mpv.conf", dest: "$HOME/.config/mpv" }

- name: Copy asciinema player config files
  copy:
      src:  "{{ item }}"
      dest: "$HOME/Documents/terminal_logs"
  loop:
      - "asciinema-player.css"
      - "asciinema-player.min.js"
      - "asciinema_player.html"

- name: Open pgp files with seahorse
  command: xdg-mime default org.gnome.seahorse.Application.desktop application/pgp-keys

- name: Create cronjob to zip up logs from terminal recording program
  cron:
      name: "zip terminal logs"
      job: "find $HOME/Documents/terminal_logs -mtime +7 ! -name 'asciinema*' -exec bzip2 {} \\;"
      hour: "13"
      minute: "0"

- name: Copy opensubtitlesdownload script
  template:
      src: opensubtitles.j2
      dest: $HOME/.local/share/nautilus/scripts/opensubtitles.py

- name: Copy other useful nautilus scripts
  copy:
      src:  "{{ item }}"
      dest: "$HOME/.local/share/nautilus/scripts"
  loop:
      - "nautilus-renamer.py"
      - "nautilus-resize-image"
