---
- name: Install python3-pip
  apt:
      name: 'python3-pip'
      state: latest

- name: Install mariadb
  apt:
      name: mariadb-server
      state: latest

- name: Make sure pymysql is installed
  pip:
      name: pymysql
      state: present
      executable: pip3

- name: Create database for each site
  mysql_db: 
    name={{ wp_db_name }}
    state=present
    login_unix_socket=/var/run/mysqld/mysqld.sock
    login_host={{ wp_db_host }}
    login_user={{ mysql_db_user}}
    login_password={{ mysql_db_password }}
  register: wp_mysql_db_create

- name: Copy saved database to server
  copy: 
    src={{ wp_database_backup }}
    dest=/tmp/dbtorestore.sql
  when: wp_mysql_site_restore_saved_db|bool

- name: Create/assign database user to db and grant permissions
  mysql_user: 
    name={{ wp_db_user }}
    password={{ wp_db_password }}
    priv='{{ wp_db_name }}.*:ALL'
    state=present
    login_unix_socket=/var/run/mysqld/mysqld.sock
    login_host={{ wp_db_host }}
    login_user={{ mysql_db_user }}
    login_password={{ mysql_db_password }}
  tags: dbuser

- name: Import saved database
  mysql_db: 
    name={{ wp_db_name }}
    state=import
    target=/tmp/dbtorestore.sql
    login_host={{ wp_db_host }}
    login_user={{ wp_db_user}}
    login_password={{ wp_db_password }}
  when: wp_mysql_site_restore_saved_db|bool
