Vagrant.configure("2") do |config|
  # boxes at https://vagrantcloud.com/search.

  config.vm.define "web" do |web|
    web.vm.box = "debian/stretch64"
    web.vm.network "private_network", ip: "10.21.21.41"
    web.vm.hostname = "stretchvm"
  end

#  config.vm.define "db" do |db|
#    db.vm.box = "debian/stretch64"
#    db.vm.network "private_network", ip: "10.21.21.42"
#    db.vm.hostname = "stretchdb"
#  end

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = 2
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../vagrant.yml"
  end
end
