Vagrant.configure("2") do |config|
  # boxes at https://vagrantcloud.com/search.

  config.vm.define "web" do |web|
    web.vm.box = "debian/bullseye64"
    web.vm.network "private_network", ip: "10.21.21.51"
    web.vm.hostname = "bullseyeweb"
  end

  #config.vm.define "db" do |db|
  #  db.vm.box = "debian/bullseye64"
  #  db.vm.network "private_network", ip: "10.21.21.61"
  #  db.vm.hostname = "bullseyedb"
  #end

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "5192"
    vb.cpus = 4
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../vagrant.yml"
    ansible.config_file = "/home/antisa/Posal/moj_ansible.cfg"
  end
end
